ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "boardType" TEXT NOT NULL DEFAULT 'free';

CREATE TABLE IF NOT EXISTS "PostVote" (
    "id" TEXT NOT NULL,
    "postId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PostVote_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "PostVote_postId_userId_key" ON "PostVote"("postId", "userId");
CREATE INDEX IF NOT EXISTS "PostVote_userId_idx" ON "PostVote"("userId");

ALTER TABLE "PostVote" DROP CONSTRAINT IF EXISTS "PostVote_postId_fkey";
ALTER TABLE "PostVote" ADD CONSTRAINT "PostVote_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PostVote" DROP CONSTRAINT IF EXISTS "PostVote_userId_fkey";
ALTER TABLE "PostVote" ADD CONSTRAINT "PostVote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
